export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column' as const,
    padding: 'var(--padding-md)',
    border: 'none',
    borderRadius: 'var(--border-radius-md)',
    marginBottom: 'var(--padding-lg)',
    backgroundColor: 'var(--color-gray-100)',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
    cursor: 'default',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 'var(--padding-md)',
  },
  title: {
    fontWeight: 'var(--font-weight-semibold)',
    fontSize: 'var(--font-size-md-1)',
    color: 'var(--color-black)',
  },
  dragHandle: {
    cursor: 'grab',
    padding: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    '&:active': {
      cursor: 'grabbing',
    },
  },
  contentArea: {
    width: '100%',
    marginBottom: 'var(--padding-md)',
  },
  imagePlaceholder: {
    width: '100%',
    minHeight: '200px',
    borderRadius: 'var(--border-radius-sm)',
    backgroundColor: '#FFFFFF',
    display: 'flex',
    alignItems: 'flex-start',
    padding: 'var(--padding-md)',
  },
  smallImageContainer: {
    width: '80px',
    height: '80px',
    borderRadius: 'var(--border-radius-sm)',
    position: 'relative' as const,
    overflow: 'hidden' as const,
    cursor: 'pointer',
    flexShrink: 0,
    '&:hover': {
      opacity: 0.9,
    },
  },
  smallImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover' as const,
    borderRadius: 'var(--border-radius-sm)',
  },
  emptyImagePlaceholder: {
    width: '100%',
    height: '100%',
    borderRadius: 'var(--border-radius-sm)',
    backgroundColor: 'var(--color-gray-200)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative' as const,
  },
  imageIcon: {
    fontSize: '40px',
    color: 'var(--color-gray-400)',
  },
  imageIconOverlay: {
    position: 'absolute' as const,
    bottom: '8px',
    right: '8px',
    width: '32px',
    height: '32px',
    borderRadius: 'var(--border-radius-sm)',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  smallImageIcon: {
    fontSize: '18px',
    color: '#FFFFFF',
  },
  addContentButton: {
    width: '100%',
    backgroundColor: '#D6E0F5',
    color: 'var(--color-black)',
    borderRadius: 'var(--border-radius-2xl)',
    padding: 'var(--padding-sm) var(--padding-xl)',
    fontSize: 'var(--font-size-md-1)',
    fontWeight: 'var(--font-weight-semibold)',
    textTransform: 'none' as const,
    marginBottom: 'var(--padding-md)',
    '&:hover': {
      backgroundColor: '#C5D4F0',
    },
  },
  stripeButton: {
    width: '100%',
    backgroundColor: '#000000',
    color: '#FFFFFF',
    borderRadius: 'var(--border-radius-2xl)',
    padding: 'var(--padding-sm) var(--padding-xl)',
    fontSize: 'var(--font-size-md-1)',
    fontWeight: 'var(--font-weight-semibold)',
    textTransform: 'none' as const,
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--padding-sm)',
    '&:hover': {
      backgroundColor: '#1a1a1a',
    },
  },
  stripeLogo: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '20px',
    height: '20px',
    borderRadius: '4px',
    backgroundColor: '#FFFFFF',
    color: '#000000',
    fontSize: 'var(--font-size-sm)',
    fontWeight: 'var(--font-weight-bold)',
    fontFamily: 'Arial, sans-serif',
  },

  dragHandleIcon: {
    fontSize: '20px',
    color: 'var(--color-gray-500)',
  },

  addIcon: {
    fontSize: '16px',
  },
};
